version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    networks:
      - cluster_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow app to control Docker

networks:
  cluster_network:
    driver: bridge
    name: cluster_network  # Explicitly name the network